### ISSUE TITLE
Category list generates incorrect URL for Edit

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/contact_forms#1]
### Steps to reproduce

1. Install and enable contact_forms module
2. Navigate to admin/structure/contact
3. Click Edit (under 'Operations') link for any category

### Expected result
Configuration form opens for that category

###Actual result
Page reloads - no config form opens.
The cause of this is that the URL is for admin/structure/contact/**edit**/1 rather than admin/structure/contact/**configure**/1
![chrome_PGSP6JyIkW](https://user-images.githubusercontent.com/20357797/118364844-1b220880-b592-11eb-9ab7-263e46ae87ef.png)

**Comment by yorkshire-pudding** [comment]
FYI @behindthepage

**Comment by klonos** [comment]
FTR, the PR looks good to me 👍🏼

**Comment by bugfolder** [comment]
Verified the problem. Tested the PR. WFM.

**Comment by behindthepage** [comment]
Thanks @yorkshire-pudding, @klonos and @bugfolder
