### ISSUE TITLE
Error message when all categories are deleted and new category is created

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/contact_forms#3]
### Steps to reproduce

1. Enable the contact_forms module
2. Go to the configuration screen (Structure > Contact Form > List Categories)
3. Delete all existing categories
4. Create a new category and save it

#### Expected
Category saves and returns to list of categories with success message

#### Actual
Category saves and returns to list of categories with success message but also with error message

> Notice: Undefined variable: cids in contact_forms_edit_form_submit() (line 237 of /home/example1/example.com/modules/contact_forms/contact_forms.module).
> Warning: max(): When only one parameter is given, it must be an array in contact_forms_edit_form_submit() (line 237 of /home/example1/example.com/modules/contact_forms/contact_forms.module).

![MPJNGwB3ZR](https://user-images.githubusercontent.com/20357797/124287283-bf164200-db47-11eb-9ceb-a65f5ef6301e.gif)

Worked out the fix. Pull request to come shortly

**Comment by yorkshire-pudding** [comment]
@behindthepage 
Please note this issue and a pull request to fix it.
Thanks
Martin

**Comment by behindthepage** [comment]
Thanks @yorkshire-pudding. Well spotted and nicely solved.
